routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['middleware' => 'lang'], function() {

    //SITE - todas as rotas em portugues
    Route::get('/', 'SiteController@getIndex')->name('home');
    Route::get('/logout', 'SiteController@getLogout')->name('logout');

    Route::get('/elencos', 'SiteController@getElencos')->name('elencos');
    Route::post('/elencos', 'SiteController@postElencos');

    Route::get('/elenco/{slug}', 'SiteController@getElencoPerfil')->name('elencos.profile');

    Route::get('/trabalhos', 'SiteController@getTrabalhos')->name('trabalhos');
    Route::get('/trabalho/{slug}', 'SiteController@getTrabalho');

    Route::get('/agencia', 'SiteController@getAgencia')->name('agencia');
    Route::get('/contato', 'SiteController@getContato')->name('contato');
    Route::post('/send', 'SiteController@sendContact')->name('send');


    Route::get('/cadastro', 'SiteController@getCadastro')->name('cadastro');

    Route::group(['middleware'=> ['check.agenciado']], function(){
        Route::get('/perfil', 'SiteController@getProfle')->name('perfil');
        Route::get('/perfil/editar', 'SiteController@getProfleEditar');
    });

     //Cliente
     Route::group(['middleware'=> ['check.cliente']], function(){
         Route::get('/cliente', 'SiteController@Cliente')->name('cliente');
         Route::get('/cliente/editar', 'SiteController@getClienteEditar');
     });
});


Route::get('/login/facebook','SocialAuthController@login');
Route::get('/retorno/facebook','SocialAuthController@retorno');

Route::get('/login/facebook2','SocialAuthController@login2');
Route::get('/retorno/facebook2','SocialAuthController@retorno2');





// Route::group(['middleware' => 'SiteLogin'], function(){

// });

Auth::routes();

//DASHBOARD - todas as rotas em ingles

Route::get('/admin', function () {
    return redirect()->route('login');
});

Route::post('/login-agenciado', 'SiteController@LoginAgenciado');
Route::post('/registrar-agenciado', 'SiteController@RegisterAgenciado');

Route::post('/login-cliente', 'SiteController@LoginCliente');
Route::post('/registrar-cliente', 'SiteController@RegisterCliente');

Route::group(['middleware' => ['auth']], function () {

    // Dashboard
    Route::view('/dashboard', 'dashboard');

    // Cart
    Route::resource('/carts', 'CartController');
    Route::get('/carts/{cart}/preview/{profile}', 'CartController@previewPDF')->name('profile.preview');
    Route::get('/carts/{cart}/send', 'CartController@sendCart')->name('carts.send');

    // Profile
    Route::resource('/profiles', 'ProfileController');
    Route::get('/profiles/solicitation', 'ProfileController@solicitation');
    Route::resource('/profiles', 'ProfileController');

    // Skill
    Route::resource('/skills', 'SkillController');

    // Client
    Route::get('/clients/solicitation', 'ClientController@solicitation');
    Route::get('/clients/awaiting', 'ClientController@awaiting');
    Route::resource('/clients', 'ClientController');

    // Post
    Route::resource('/posts', 'PostController');

    // User
    Route::get('/profile', 'UserController@profile');
    Route::post('/profile', 'UserController@updateProfile');

    // Profile Change Request
    Route::get('/profileChangeRequest/{id}', 'ProfileChangeRequestsController@accept')
        ->name('profileChangeRequests.accept');
    // Route::post('/profileChangeRequest/{id}', 'ProfileChangeRequestsController@accept')
    //     ->name('profileChangeRequests.accept');

    Route::resource('/users', 'UserController');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'level', 'password', 'status'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function profile()
    {
        return $this->hasOne(Profile::class);
    }

    public function client()
    {
        return $this->hasOne(Client::class);
    }

    public function medias()
    {
        return $this->morphMany('App\Media', 'entity');
    }

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = bcrypt($value);
    }

    static function getLogin($email, $password){
        $user = parent::where('email',$email ) ->where('level', 3)->first();

        if( $user ){
            if(!$user->password ){
                return ['message' => 'incomplete'];
            }
    
            if(password_verify ( $password , $user->password ) ){
                return $user;
            }
        }

        return ['message' => 'notfound'];

    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Media;
use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::where('level', 1)->orderBy('name', 'asc')->latest()->paginate(10);

        return view('users.index', compact('users'))
            ->with('i', (request()->input('page', 1) - 1) * 10);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'name' => 'required',
            'email' => 'required|email|unique:users',
            'password' => 'required|min:8|confirmed',
        ]);

        $user = User::create($request->all());

        if ($request->hasFile('image')) {
            $media = new Media;

            $slug = str_slug($request->name, "-");

            $image = $request->file('image');
            $name = "{$slug}.{$request->image->extension()}";
            $path = "/uploads/users";
            $destinationPath = public_path($path);
            $imagePath = $destinationPath . "/" . $name;
            $image->move($destinationPath, $name);

            $media->path = $path . "/" . $name;
            $media->type = "image";

            $user->medias()->save($media);
        }

        return redirect()->route('users.index')
            ->with('success', 'Usuário criado com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        request()->validate([
            'name' => 'required',
            'email' => 'required|email',
        ]);

        $data = $request->all();

        if (!$request->password) {
            $data = $request->except('password');
        }

        $user->update($data);

        if ($request->hasFile('image')) {
            $user->medias()->delete();

            $media = new Media;
            $slug = str_slug($request->name, "-");
            $image = $request->file('image');
            $name = "{$slug}.{$request->image->extension()}";
            $path = "/uploads/users";
            $destinationPath = public_path($path);
            $imagePath = $destinationPath . "/" . $name;
            $image->move($destinationPath, $name);

            $media->path = $path . "/" . $name;
            $media->type = "image";

            $user->medias()->save($media);
        }

        return redirect()->route('users.index')
            ->with('success', 'Usuário atualizado com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return redirect()->route('users.index')
            ->with('success', 'Usuário deletado com sucesso!');
    }

    public function profile()
    {
        $user = auth()->user();

        return view('profile.index', compact('user'));
    }

    public function updateProfile(Request $request)
    {
        $user = auth()->user();
        request()->validate([
            'name' => 'required',
            'email' => 'required|email',
        ]);

        $data = $request->all();

        if (!$request->password) {
            $data = $request->except('password');
        }

        $user->update($data);

        if ($request->hasFile('image')) {
            $user->medias()->delete();

            $media = new Media;
            $slug = str_slug($request->name, "-");
            $image = $request->file('image');
            $name = "{$slug}.{$request->image->extension()}";
            $path = "/uploads/users";
            $destinationPath = public_path($path);
            $imagePath = $destinationPath . "/" . $name;
            $image->move($destinationPath, $name);

            $media->path = $path . "/" . $name;
            $media->type = "image";

            $user->medias()->save($media);
        }

        return redirect()->back()
            ->with('success', 'Seu perfil foi atualizado com sucesso!');
    }
}

resources/views/users/create.blade.php
@extends('layouts.backend')

@section('content')
<!-- Hero -->
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Usuários</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">App</li>
                    <li class="breadcrumb-item">Usuários</li>
                    <li class="breadcrumb-item active" aria-current="page">Novo</li>
                </ol>
            </nav>
        </div>
   </div>
</div>
<!-- END Hero -->
<div class="content">
    <a href="{{ route('users.index') }}" class="btn btn-primary push">Voltar</a>

    @if ($errors->any())
        <div class="alert alert-danger" role="alert">
            <p class="mb-0">Verifique os seguintes erros:</p>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Usuários</h3>
        </div>
        <div class="block-content">
                <form action="{{ route('users.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <h2 class="content-heading pt-0">Novo usuário de sistema</h2>
                <div class="row push">
                    <div class="col-lg-4">
                        <p class="text-muted">
                            Hora de criar um novo usuário para o sistema. Para isso basta preencher os dados que seguem. Vale lembrar que os usuários cadastrados aqui terão acesso total ao sistema.
                        </p>
                    </div>
                    <div class="col-lg-8 col-xl-5">
                        <div class="form-group">
                            <label for="example-text-input">Nome</label>
                            <input type="text" class="form-control" name="name" placeholder="">
                        </div>
                        <div class="form-group">
                            <label for="example-text-input">Email</label>
                            <input type="email" class="form-control" name="email" placeholder="">
                        </div>
                        <div class="form-group">
                            <label for="example-text-input">Senha</label>
                            <input type="password" class="form-control" name="password" placeholder="">
                        </div>
                        <div class="form-group">
                            <label for="example-text-input">Confirma senha</label>
                            <input type="password" class="form-control" name="password_confirmation" placeholder="">
                        </div>
                        <div class="form-group" id="type-image">
                            <label class="d-block" for="image">Foto do perfil</label>
                            <input type="file" id="image" name="image">
                        </div>
                        <div class="form-group">
                            <label class="d-block">Status</label>
                            <div class="custom-control custom-radio custom-control-inline custom-control-primary">
                                <input type="radio" class="custom-control-input" id="status-active" name="status" checked value="1">
                                <label class="custom-control-label" for="status-active">Ativo</label>
                            </div>
                            <div class="custom-control custom-radio custom-control-inline custom-control-primary">
                                <input type="radio" class="custom-control-input" id="status-inactive" name="status" value="2">
                                <label class="custom-control-label" for="status-inactive">Inativo</label>
                            </div>
                        </div>
                        <input type="hidden" name="level" value="1">
                        <div class="form-group"> 
                            <button type="submit" class="btn btn-primary">Salvar</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.backend')

@section('content')
<!-- Hero -->
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Usuários</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">App</li>
                    <li class="breadcrumb-item">Usuários</li>
                    <li class="breadcrumb-item active" aria-current="page">Edição</li>
                </ol>
            </nav>
        </div>
   </div>
</div>
<!-- END Hero -->
<div class="content">
    <a href="{{ route('users.index') }}" class="btn btn-primary push">Voltar</a>

    @if ($errors->any())
        <div class="alert alert-danger" role="alert">
            <p class="mb-0">Verifique os seguintes erros:</p>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Usuários</h3>
        </div>
        <div class="block-content">
                <form action="{{ route('users.update', $user->id) }}" method="POST" enctype="multipart/form-data">

                @csrf
                @method('PUT')

                <h2 class="content-heading pt-0">Editando usuário de sistema</h2>
                <div class="row push">
                    <div class="col-lg-4">
                        <p class="text-muted">
                            Hora de editar um usuário do sistema. Para isso basta preencher os dados que seguem. Vale lembrar que os usuários cadastrados aqui tem acesso total ao sistema.
                        </p>
                    </div>
                    <div class="col-lg-8 col-xl-5">
                        <div class="form-group">
                            <label for="example-text-input">Nome</label>
                            <input type="text" class="form-control" name="name" value="{{ old('name', $user->name) }}">
                        </div>
                        <div class="form-group">
                            <label for="example-text-input">Email</label>
                            <input type="email" class="form-control" name="email" value="{{ old('email', $user->email) }}">
                        </div>
                        <div class="form-group">
                            <label for="example-text-input">Senha</label>
                            <input type="password" class="form-control" name="password">
                        </div>
                        <div class="form-group">
                            <label for="example-text-input">Confirma senha</label>
                            <input type="password" class="form-control" name="password_confirmation">
                        </div>
                        <div class="form-group" id="type-image">
                            <label class="d-block" for="image">Foto do perfil</label>
                            <input type="file" id="image" name="image">
                        </div>
                        <div class="form-group">
                            <label class="d-block">Status</label>
                            <div class="custom-control custom-radio custom-control-inline custom-control-primary">
                            <input type="radio" class="custom-control-input" id="status-active" name="status" {{ $user->status == 1 ? 'checked' : '' }} value="1">
                                <label class="custom-control-label" for="status-active">Ativo</label>
                            </div>
                            <div class="custom-control custom-radio custom-control-inline custom-control-primary">
                                <input type="radio" class="custom-control-input" id="status-inactive" name="status" {{ $user->status == 2 ? 'checked' : '' }} value="2">
                                <label class="custom-control-label" for="status-inactive">Inativo</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Salvar</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.backend')

@section('content')
<!-- Hero -->
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Usuários</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">App</li>
                    <li class="breadcrumb-item">Usuários</li>
                    <li class="breadcrumb-item active" aria-current="page">Todos</li>
                </ol>
            </nav>
        </div>
   </div>
</div>
<!-- END Hero -->
<div class="content">
    <a href="{{ route('users.create') }}" class="btn btn-primary push">Novo usuário</a>

    @if ($message = Session::get('success'))
    <div class="alert alert-success d-flex align-items-center" role="alert">
        <div class="flex-00-auto">
            <i class="fa fa-fw fa-check"></i>
        </div>
        <div class="flex-fill ml-3">
            <p class="mb-0">{{$message}}</p>
        </div>
    </div>
    @endif

    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Usuários do sistema</h3>
        </div>
        <div class="block-content">
            <p>
                Este é o lugar que você encontra todos os usuários que possuem acesso ao sistema de administração da Pharos Elenco!
            </p>
            <table class="table table-striped table-hover table-borderless table-vcenter font-size-sm">
                <thead>
                    <tr class="text-uppercase">
                        <th class="text-center" style="width: 100px;">
                            <i class="far fa-user"></i>
                        </th>
                        <th>NOME</th>
                        <th class="text-center" style="width: 200px;">CADASTRO</th>
                        <th class="text-center" style="width: 100px;">ACESSO</th>
                        <th class="text-center" style="width: 100px;">STATUS</th>
                        <th class="text-center" style="width: 100px;">AÇÕES</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($users as $user)
                    <tr>
                        <td class="text-center">
                            @if ($user->medias->first())
                            <img class="img-avatar img-avatar48" src="{{$user->medias->first()->path}}" alt="">
                            @else
                            <img class="img-avatar img-avatar48" src="https://api.adorable.io/avatars/48/{{$user->email}}" alt="">
                            @endif
                        </td>
                        <td>
                            <div class="font-w600 font-size-base">{{ $user->name }}</div>
                            <div class="text-muted">{{$user->email}}</div>
                        </td>
                        <td class="text-center font-size-base">
                            {{ $user->created_at->format('d/m/Y') }}
                        </td>
                        <td class="text-center">
                            @if ($user->level == 1)
                            <span class="badge badge-success">ADMIN</span>
                            @endif
                        </td>
                        <td class="text-center">
                            @if ($user->status == 1)
                            <span class="badge badge-success">ATIVO</span>
                            @else
                            <span class="badge badge-danger">INATIVO</span>
                            @endif
                        </td>
                        <td class="text-center">
                            <div class="btn-group">
                                <a href="{{ route('users.edit', $user->id) }}" class="btn btn-sm btn-primary" data-toggle="tooltip" title="Editar" data-placement="left">
                                    <i class="fa fa-pencil-alt"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection