routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['middleware' => 'lang'], function() {

    //SITE - todas as rotas em portugues
    Route::get('/', 'SiteController@getIndex')->name('home');
    Route::get('/logout', 'SiteController@getLogout')->name('logout');

    Route::get('/elencos', 'SiteController@getElencos')->name('elencos');
    Route::post('/elencos', 'SiteController@postElencos');

    Route::get('/elenco/{slug}', 'SiteController@getElencoPerfil')->name('elencos.profile');

    Route::get('/trabalhos', 'SiteController@getTrabalhos')->name('trabalhos');
    Route::get('/trabalho/{slug}', 'SiteController@getTrabalho');

    Route::get('/agencia', 'SiteController@getAgencia')->name('agencia');
    Route::get('/contato', 'SiteController@getContato')->name('contato');
    Route::post('/send', 'SiteController@sendContact')->name('send');


    Route::get('/cadastro', 'SiteController@getCadastro')->name('cadastro');

    Route::group(['middleware'=> ['check.agenciado']], function(){
        Route::get('/perfil', 'SiteController@getProfle')->name('perfil');
        Route::get('/perfil/editar', 'SiteController@getProfleEditar');
    });

     //Cliente
     Route::group(['middleware'=> ['check.cliente']], function(){
         Route::get('/cliente', 'SiteController@Cliente')->name('cliente');
         Route::get('/cliente/editar', 'SiteController@getClienteEditar');
     });
});


Route::get('/login/facebook','SocialAuthController@login');
Route::get('/retorno/facebook','SocialAuthController@retorno');

Route::get('/login/facebook2','SocialAuthController@login2');
Route::get('/retorno/facebook2','SocialAuthController@retorno2');





// Route::group(['middleware' => 'SiteLogin'], function(){

// });

Auth::routes();

//DASHBOARD - todas as rotas em ingles

Route::get('/admin', function () {
    return redirect()->route('login');
});

Route::post('/login-agenciado', 'SiteController@LoginAgenciado');
Route::post('/registrar-agenciado', 'SiteController@RegisterAgenciado');

Route::post('/login-cliente', 'SiteController@LoginCliente');
Route::post('/registrar-cliente', 'SiteController@RegisterCliente');

Route::group(['middleware' => ['auth']], function () {

    // Dashboard
    Route::view('/dashboard', 'dashboard');

    // Cart
    Route::resource('/carts', 'CartController');
    Route::get('/carts/{cart}/preview/{profile}', 'CartController@previewPDF')->name('profile.preview');
    Route::get('/carts/{cart}/send', 'CartController@sendCart')->name('carts.send');

    // Profile
    Route::resource('/profiles', 'ProfileController');
    Route::get('/profiles/solicitation', 'ProfileController@solicitation');
    Route::resource('/profiles', 'ProfileController');

    // Skill
    Route::resource('/skills', 'SkillController');

    // Client
    Route::get('/clients/solicitation', 'ClientController@solicitation');
    Route::get('/clients/awaiting', 'ClientController@awaiting');
    Route::resource('/clients', 'ClientController');

    // Post
    Route::resource('/posts', 'PostController');

    // User
    Route::get('/profile', 'UserController@profile');
    Route::post('/profile', 'UserController@updateProfile');

    // Profile Change Request
    Route::get('/profileChangeRequest/{id}', 'ProfileChangeRequestsController@accept')
        ->name('profileChangeRequests.accept');
    // Route::post('/profileChangeRequest/{id}', 'ProfileChangeRequestsController@accept')
    //     ->name('profileChangeRequests.accept');

    Route::resource('/users', 'UserController');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'subtitle', 'body', 'slug', 'status'
    ];

    public function medias()
    {
        return $this->morphMany('App\Media', 'entity');
    }

    public function profiles() 
    {
        return $this->belongsToMany('App\Profile')->withTimestamps();
    }
    
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Media;
use App\Notices;
use App\Post;
use App\Profile;
use App\Http\Controllers\Api\HelperController;
use Illuminate\Http\Request;


class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Notices::orderBy('created_at', 'desc')->latest()->paginate(10);

        return view('posts.index', compact('posts'))
            ->with('i', (request()->input('page', 1) - 1) * 10);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $profiles = Profile::all();

        return view('posts.create', compact('profiles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $Helper = app(HelperController::class);
        request()->validate([
            'title' => 'required',
            'description' => 'required|min:10',

        ]);
        $video = $Helper->linkSanatizer($request->get('video'));
        $agenciado = $request->get('agenciado') ? json_encode( $request->get('agenciado') ) : null;
        $slug = str_slug($request->title, '-');

        $request->merge([
            'slug' => $slug,
            'video'=> $video,
            'agenciado'=> $agenciado,
            ]);

        if ($request->hasFile('image')) {

            $image = $request->file('image');
            $name = "{$slug}.{$request->image->extension()}";
            $path = "/uploads/notices";
            $destinationPath = public_path($path);
            $image->move($destinationPath, $name);
            $request->merge(['media'=> $name]);
            $request->merge(['media_type'=>'image']);
        }

        $post = Notices::create($request->all());

        return redirect()->route('posts.index')
            ->with('success', 'Noticias criada com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Notices::find($id);
        $profile = Profile::select('user_id','fancy_name')->orderBy('fancy_name', 'ASC')->get();

        if ($post->agenciado){
            $agenciados = json_decode($post->agenciado);
            foreach($profile as $key => $value){
                if( in_array(  $value->user_id, json_decode($post->agenciado) ) ){
                    $profiles[] = [
                        'user_id' => $value->user_id,
                        'fancy_name' => $value->fancy_name,
                        'selected' => true,
                    ];
                } else {
                    $profiles[] = [
                        'user_id' => $value->user_id,
                        'fancy_name' => $value->fancy_name,
                        'selected' => false,
                    ];
                }

            }
        } else {
            foreach($profile as $key => $value){
                $profiles[] = [
                    'user_id' => $value->user_id,
                    'fancy_name' => $value->fancy_name,
                    'selected' => false,
                ];
            }
        }
        return view('posts.edit', compact( 'post', 'profiles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $Helper = app(HelperController::class);

//        request()->validate([
//            'title' => 'required',
//            'description' => 'required|min:10',
//            'media' => 'required',
//        ]);
        $data = $request->all();

        $agenciado = $request->get('agenciado') ? json_encode( $request->get('agenciado') ) : null;
        $slug = str_slug($request->title, '-');
        $request->merge([
            // 'slug' => $slug,
            'agenciado'=> $agenciado,
            ]);

        if($request->get('video')){
            if( strpos( $request->get('video'),'embed') > 0 ){
                $video = $request->get('video');
            } else {
                $video = $Helper->linkSanatizer( $request->get('video') );
            }
            $request->merge([
                'video'=> $video,
            ]);
        }
        // dd($request->all());
        if ($request->hasFile('image')) {

            $image = $request->file('image');
            $name = "{$slug}.{$request->image->extension()}";
            $path = "/uploads/notices";
            $destinationPath = public_path($path);
            $image->move($destinationPath, $name);
            $request->merge(['media'=> $name]);
            $request->merge(['media_type'=>'image']);
        }

        //because of the link sanitazer, I cant let videos null pass throught
        $data = $request->all();
        if( $request->get('video') == null ){
            unset( $data['video'] );
        }


        Notices::find($id)->update($data);

        return redirect()->route('posts.index')
            ->with('success', 'Noticia atualizada com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      Notices::find($id)->delete();

        return redirect()->route('posts.index')
            ->with('success', 'Postagem deletada com sucesso!');
    }
}

resources/views/posts/create.blade.php
@extends('layouts.backend')

@section('content')
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Trabalhos</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">App</li>
                    <li class="breadcrumb-item">Trabalhos</li>
                    <li class="breadcrumb-item active" aria-current="page">Novo</li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<div class="content">
    <a href="{{ route('posts.index') }}" class="btn btn-primary push">Voltar</a>

    @if ($errors->any())
        <div class="alert alert-danger" role="alert">
            <p class="mb-0">Verifique os seguintes erros:</p>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Postagem</h3>
        </div>
        <div class="block-content">
                <form action="{{ route('posts.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <h2 class="content-heading pt-0">Nova postagem</h2>
                <div class="row push">
                    <div class="col-lg-4">
                        <p class="text-muted">
                            Hora de realizar uma postagem. Cadastrar um novo projeto realizado, uma novidade ou o que você julgar interessante para seus visitantes.
                        </p>
                    </div>
                    <div class="col-lg-8 col-xl-5">
                        <div class="form-group">
                            <label for="title">Título *</label>
                            <input type="text" class="form-control" name="title" placeholder="" value="{{ old('title') }}">
                        </div>
                        <div class="form-group">
                            <label for="subtitle">Subtítulo</label>
                            <input type="text" class="form-control" name="subtitle" placeholder="" value="{{ old('subtitle') }}">
                        </div>
                        <div class="form-group">
                            <label for="body">Conteúdo *</label>
                            <textarea type="text" class="form-control" name="description" rows="10" placeholder="">{{ old('description') }}</textarea>
                        </div>

                        <div class="form-group">
                            <label for="subtitle">Foto</label>
                            <input type="file" class="form-control" name="image" placeholder="">
                        </div>

                        <div class="form-group">
                            <label for="subtitle">Video</label>
                            <input type="text" class="form-control" name="video" placeholder="Adicione um vídeo" value="{{ old('video') }}">
                        </div>

                        <div class="form-group">
                            <label for="subtitle">Agenciado <span id="normal_PC"><small> (segure <span style="color: darkred;">ctrl</span> e clique para selecionar mais de um)</small></label></span> <span id="mac_PC" style="display:none;"><small> (segure <span style="color: darkred;">cmd</span> e clique para selecionar mais de um)</small></label></span>
                            <script>
                                if( navigator.appVersion.indexOf('Macintosh') > 0){
                                    document.getElementById('normal_PC').style.display = 'none'
                                    document.getElementById('mac_PC').style.display = 'inline-block'
                                }
                            </script>
                            <div style="width: 100%; background-color: #eee; border: 1px solid #d8dfed; border-radius: 3px; padding: 10px;">
                                <select name="agenciado[]" id="" style="width:100%; border: none;" multiple>
                                    <option value="">-- Selecione --</option>
                                    @foreach(\app\Profile::select('user_id','fancy_name')->orderBy('fancy_name', 'ASC')->get() as $key => $value)
                                        <option value="{{ $value->user_id }}">{{ $value->fancy_name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-group"> 
                            <button type="submit" class="btn btn-primary">Salvar</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection
@section('js_after')

    <script src="https://cloud.tinymce.com/4/tinymce.min.js"></script>
    <script>tinymce.init({selector:'textarea'});</script>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.backend')
<?php
?>

@section('content')
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Trabalhos</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">App</li>
                    <li class="breadcrumb-item">Trabalhos</li>
                    <li class="breadcrumb-item active" aria-current="page">Edição</li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<div class="content">
    <a href="{{ route('posts.index') }}" class="btn btn-primary push">Voltar</a>

    @if ($errors->any())
        <div class="alert alert-danger" role="alert">
            <p class="mb-0">Verifique os seguintes erros:</p>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Postagem</h3>
        </div>
        <div class="block-content">
            <form action="{{ route('posts.update', $post->id) }}" method="POST" enctype="multipart/form-data">
                
                @csrf
                @method('PUT')

                <h2 class="content-heading pt-0">Editando postagem</h2>
                <div class="row push">
                    <div class="col-lg-4">
                        <p class="text-muted">
                            Ops, algo precisa ser consertado. Hora de editar uma postagem ;)
                        </p>
                    </div>
                    <div class="col-lg-8 col-xl-5">
                        
                        {{--@if ($post->medias()->count() > 0 && @$post->medias[0]->type == 'image')--}}
                        {{--<div class="row items-push">--}}
                            {{--<div class="col-md-4 animated fadeIn">--}}
                                {{--<div class="options-container">--}}
                                    {{--<img class="img-fluid options-item" src="{{asset(@$post->medias[0]->path)}}" alt="">--}}
                                    {{--<div class="options-overlay bg-primary-dark-op">--}}
                                        {{--<div class="options-overlay-content">--}}
                                            {{--<h3 class="h4 text-white mb-2">{{$post->slug}}</h3>--}}
                                        {{--</div>--}}
                                    {{--</div>--}}
                                {{--</div>--}}
                            {{--</div>--}}
                        {{--</div>--}}
                        {{--@endif--}}

                        <div class="form-group">
                            <label for="title">Título *</label>
                            <input type="text" class="form-control" name="title" placeholder="" value="{{ old('title', $post->title) }}">
                        </div>
                        <div class="form-group">
                            <label for="subtitle">Subtítulo</label>
                            <input type="text" class="form-control" name="subtitle" placeholder="" value="{{ old('subtitle', $post->subtitle) }}">
                        </div>
                        <div class="form-group">
                            <label for="body">Conteúdo *</label>
                            <textarea type="text" class="form-control" name="description" rows="10" placeholder="">{{ old('body', $post->description) }}</textarea>
                        </div>

                        <div class="form-group">
                            <label for="subtitle">FOTO</label>
                            <input type="file" class="form-control" name="image" placeholder="">
                        </div>




                        {{--<div class="form-group">--}}
                            {{--@if ($post->medias()->count() > 0)--}}
                            {{--<div class="custom-control custom-radio custom-control-inline custom-control-primary">--}}
                                {{--<input type="radio" class="custom-control-input" id="typeImage" name="typeFile" value="typeImage" {{ $post->medias[0]->type == 'image' ? 'checked' : '' }}>--}}
                                {{--<label class="custom-control-label" for="typeImage">Imagem</label>--}}
                            {{--</div>--}}
                            {{--<div class="custom-control custom-radio custom-control-inline custom-control-primary">--}}
                                {{--<input type="radio" class="custom-control-input" id="typeMovie" name="typeFile" value="typeMovie" {{ $post->medias[0]->type == 'movie' ? 'checked' : '' }}>--}}
                                {{--<label class="custom-control-label" for="typeMovie">Vídeo</label>--}}
                            {{--</div>--}}
                            {{--@else--}}
                            {{--<div class="custom-control custom-radio custom-control-inline custom-control-primary">--}}
                                {{--<input type="radio" class="custom-control-input" id="typeImage" name="typeFile" value="typeImage" checked }}>--}}
                                {{--<label class="custom-control-label" for="typeImage">Imagem</label>--}}
                            {{--</div>--}}
                            {{--<div class="custom-control custom-radio custom-control-inline custom-control-primary">--}}
                                {{--<input type="radio" class="custom-control-input" id="typeMovie" name="typeFile" value="typeMovie">--}}
                                {{--<label class="custom-control-label" for="typeMovie">Vídeo</label>--}}
                            {{--</div>--}}
                            {{--@endif--}}
                        {{--</div>--}}
                        
                        {{--@if ($post->medias()->count() > 0)--}}
                        {{--<div class="form-group {{ $post->medias[0]->type == 'movie' ? 'type-image-disabled' : '' }}" id="type-image">--}}
                            {{--<label class="d-block" for="image">Anexar imagem</label>--}}
                            {{--<input type="file" id="image" name="image">--}}
                        {{--</div>--}}

                        {{--<div class="form-group {{ $post->medias[0]->type == 'image' ? 'type-movie-disabled' : '' }}" id="type-movie">--}}
                            {{--<label for="movie">Youtube link</label>--}}
                            {{--<input type="text" class="form-control" name="movie" placeholder="" value="{{ $post->medias[0]->type == 'movie' ? $post->medias[0]->path : '' }}">--}}
                        {{--</div>--}}
                        {{--@else--}}
                        {{--<div class="form-group" id="type-image">--}}
                            {{--<label class="d-block" for="image">Anexar imagem</label>--}}
                            {{--<input type="file" id="image" name="image">--}}
                        {{--</div>--}}
                        {{--<div class="form-group type-movie-disabled" id="type-movie">--}}
                            {{--<label for="movie">Link do vídeo (Youtube / Vimeo)</label>--}}
                            {{--<input type="text" class="form-control" name="movie" placeholder="" value="">--}}
                        {{--</div>--}}
                        {{--@endif--}}

                        {{--<div class="form-group">--}}
                            {{--<label class="d-block">Agenciado <small>(Segure <code>CTRL</code> e clique para selecionar mais de um)</small></label>--}}
                            {{--<select class="form-control" id="profile_id" name="profile_id[]" multiple>--}}
                                {{--<option value="">-- Selecione --</option>--}}
                                {{--@foreach($profiles as $profile)--}}
                                    {{--@if ($post->profiles->contains($profile))--}}
                                    {{--<option value="{{$profile->id}}" selected>{{$profile->user->name}}</option>--}}
                                    {{--@else--}}
                                    {{--<option value="{{$profile->id}}">{{$profile->user->name}}</option>--}}
                                    {{--@endif--}}
                                {{--@endforeach--}}
                            {{--</select>--}}
                        {{--</div>--}}

                        {{--<div class="form-group">--}}
                            {{--<label class="d-block">Status</label>--}}
                            {{--<div class="custom-control custom-radio custom-control-inline custom-control-primary">--}}
                            {{--<input type="radio" class="custom-control-input" id="status-active" name="status" {{ $post->status == 1 ? 'checked' : '' }} value="1">--}}
                                {{--<label class="custom-control-label" for="status-active">Ativo</label>--}}
                            {{--</div>--}}
                            {{--<div class="custom-control custom-radio custom-control-inline custom-control-primary">--}}
                                {{--<input type="radio" class="custom-control-input" id="status-inactive" name="status" {{ $post->status == 2 ? 'checked' : '' }} value="2">--}}
                                {{--<label class="custom-control-label" for="status-inactive">Inativo</label>--}}
                            {{--</div>--}}
                        {{--</div>--}}

                        <div class="form-group">
                            <label for="subtitle">Video</label>
                            @if($post->video )
                            <div>
                                <iframe src="{{ $post->video }}" style="max-width: 100%;" frameborder="0"></iframe>
                            </div>
                            @endif
                            <input type="text" class="form-control" name="video" placeholder="Adicione um vídeo" value="{{ old('video')  }}">
                        </div>

                        <div class="form-group">
                            <label for="subtitle">Agenciado <span id="normal_PC"><small> (segure <span style="color: darkred;">ctrl</span> e clique para selecionar mais de um)</small></label></span> <span id="mac_PC" style="display:none;"><small> (segure <span style="color: darkred;">cmd</span> e clique para selecionar mais de um)</small></label></span>
                            <script>
                                if( navigator.appVersion.indexOf('Macintosh') > 0){
                                    document.getElementById('normal_PC').style.display = 'none'
                                    document.getElementById('mac_PC').style.display = 'inline-block'
                                }
                            </script>
                            <div style="width: 100%; background-color: #eee; border: 1px solid #d8dfed; border-radius: 3px; padding: 10px;">
                                <select name="agenciado[]" id="" style="width:100%; border: none;" multiple>
                                    <option value="">-- Selecione --</option>
                                    @foreach( $profiles as $key => $value)
                                        <option value="{{ $value['user_id'] }}" {{ $value['selected'] ? "selected" : '' }}>{{ $value['fancy_name'] }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-group"> 
                            <button type="submit" class="btn btn-primary">Salvar</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection
@section('js_after')

    <script src="https://cloud.tinymce.com/4/tinymce.min.js"></script>
    <script>tinymce.init({selector:'textarea'});</script>
@endsection