routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['middleware' => 'lang'], function() {

    //SITE - todas as rotas em portugues
    Route::get('/', 'SiteController@getIndex')->name('home');
    Route::get('/logout', 'SiteController@getLogout')->name('logout');

    Route::get('/elencos', 'SiteController@getElencos')->name('elencos');
    Route::post('/elencos', 'SiteController@postElencos');

    Route::get('/elenco/{slug}', 'SiteController@getElencoPerfil')->name('elencos.profile');

    Route::get('/trabalhos', 'SiteController@getTrabalhos')->name('trabalhos');
    Route::get('/trabalho/{slug}', 'SiteController@getTrabalho');

    Route::get('/agencia', 'SiteController@getAgencia')->name('agencia');
    Route::get('/contato', 'SiteController@getContato')->name('contato');
    Route::post('/send', 'SiteController@sendContact')->name('send');


    Route::get('/cadastro', 'SiteController@getCadastro')->name('cadastro');

    Route::group(['middleware'=> ['check.agenciado']], function(){
        Route::get('/perfil', 'SiteController@getProfle')->name('perfil');
        Route::get('/perfil/editar', 'SiteController@getProfleEditar');
    });

     //Cliente
     Route::group(['middleware'=> ['check.cliente']], function(){
         Route::get('/cliente', 'SiteController@Cliente')->name('cliente');
         Route::get('/cliente/editar', 'SiteController@getClienteEditar');
     });
});


Route::get('/login/facebook','SocialAuthController@login');
Route::get('/retorno/facebook','SocialAuthController@retorno');

Route::get('/login/facebook2','SocialAuthController@login2');
Route::get('/retorno/facebook2','SocialAuthController@retorno2');





// Route::group(['middleware' => 'SiteLogin'], function(){

// });

Auth::routes();

//DASHBOARD - todas as rotas em ingles

Route::get('/admin', function () {
    return redirect()->route('login');
});

Route::post('/login-agenciado', 'SiteController@LoginAgenciado');
Route::post('/registrar-agenciado', 'SiteController@RegisterAgenciado');

Route::post('/login-cliente', 'SiteController@LoginCliente');
Route::post('/registrar-cliente', 'SiteController@RegisterCliente');

Route::group(['middleware' => ['auth']], function () {

    // Dashboard
    Route::view('/dashboard', 'dashboard');

    // Cart
    Route::resource('/carts', 'CartController');
    Route::get('/carts/{cart}/preview/{profile}', 'CartController@previewPDF')->name('profile.preview');
    Route::get('/carts/{cart}/send', 'CartController@sendCart')->name('carts.send');

    // Profile
    Route::resource('/profiles', 'ProfileController');
    Route::get('/profiles/solicitation', 'ProfileController@solicitation');
    Route::resource('/profiles', 'ProfileController');

    // Skill
    Route::resource('/skills', 'SkillController');

    // Client
    Route::get('/clients/solicitation', 'ClientController@solicitation');
    Route::get('/clients/awaiting', 'ClientController@awaiting');
    Route::resource('/clients', 'ClientController');

    // Post
    Route::resource('/posts', 'PostController');

    // User
    Route::get('/profile', 'UserController@profile');
    Route::post('/profile', 'UserController@updateProfile');

    // Profile Change Request
    Route::get('/profileChangeRequest/{id}', 'ProfileChangeRequestsController@accept')
        ->name('profileChangeRequests.accept');
    // Route::post('/profileChangeRequest/{id}', 'ProfileChangeRequestsController@accept')
    //     ->name('profileChangeRequests.accept');

    Route::resource('/users', 'UserController');
});

app/Client.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $fillable = [
        'contact', 'phone_number', 'status'
    ];

    /**
     * Retonr o usuário referente ao cliente.
     *
     * @return void
     */
    public function user()
    {
        return $this->belongsTo('App\User');
    }

    /**
     * Retorna os carrinho do cliente.
     *
     * @return void
     */
    public function carts()
    {
        return $this->hasMany('App\Cart');
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Client;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;

class ClientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clients = Client::with(['user' => function ($query) {
            $query->where('level', 3)->orderBy('name', 'asc');
        }])->where('status', 1)->latest()->paginate(30);

        return view('clients.index', compact('clients'))
            ->with('i', (request()->input('page', 1) - 1) * 10);
    }

    public function awaiting()
    {
        $clients = Client::with(['user' => function ($query) {
            $query->where('level', 3)->orderBy('name', 'asc');
        }])->where('status', 2)->latest()->paginate(10);

        return view('clients.awaiting', compact('clients'))
            ->with('i', (request()->input('page', 1) - 1) * 10);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('clients.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'name' => 'required',
            'email' => 'required|email|unique:users',
            'contact' => 'required',
            'phone_number' => 'required',
            'password' => 'required|min:8|confirmed',
        ]);

        $user = User::create($request->all());

        $client = new Client();
        $client->contact = $request->contact;
        $client->phone_number = $request->phone_number;
        $client->status = $request->status;

        $user->client()->save($client);

        return redirect()->route('clients.index')
            ->with('success', 'Produtora cadastrada com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function show(Client $client)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Client  $producer
     * @return \Illuminate\Http\Response
     */
    public function edit(Client $client)
    {
        return view('clients.edit', compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Client $client)
    {
        request()->validate([
            'name' => 'required',
            'email' => 'required|email|unique:users,email,' . $client->user->id,
            'contact' => 'required',
            'phone_number' => 'required',
        ]);

        $client->update($request->all());

        $client->user->name = $request->name;
        $client->user->email = $request->email;

        $client->user->update();

        return redirect()->route('clients.index')
            ->with('success', 'Produtora atualizada com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Client  $client
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $producer)
    {
        $producer->delete();

        return redirect()->route('clients.index')
            ->with('success', 'Produtora deletada com sucesso!');
    }

    public function solicitation()
    {
        return view("clients.solicitation");
    }
}

resources/views/clients/awaiting.blade.php
@extends('layouts.backend')

@section('content')
<div class="content">
    <a href="{{ route('clients.create') }}" class="btn btn-primary push">Nova produtora</a>

    @if ($message = Session::get('success'))
    <div class="alert alert-success d-flex align-items-center" role="alert">
        <div class="flex-00-auto">
            <i class="fa fa-fw fa-check"></i>
        </div>
        <div class="flex-fill ml-3">
            <p class="mb-0">{{$message}}</p>
        </div>
    </div>
    @endif


    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Produtoras</h3>
        </div>
        <div class="block-content">
            <p>
                Aqui você encontra a lista de produtoras que estão aguardando serem aprovadas e desfrutarem dos benefícios!
            </p>
            <table class="table table-striped table-hover table-borderless table-vcenter font-size-sm">
                <thead>
                    <tr class="text-uppercase">
                        <th class="text-center" style="width: 50px;">#</th>
                        <th class="font-w700">Nome</th>
                        <th class="font-w700">E-mail</th>
                        <th class="font-w700">Cadastrado em</th>
                        <th class="d-none d-sm-table-cell font-w700">Status</th>
                        <th class="font-w700 text-center" style="width: 60px;"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($clients as $client)
                    <tr>
                        <th class="text-center" scope="row">{{ ++$i }}</th>
                        <td class="font-w600">
                            <a href="{{ route('clients.edit', $client->id) }}">{{ $client->user->name }}</a>
                        </td>
                        <td>{{ $client->user->email }}</td>
                        <td class="d-none d-sm-table-cell"><em class="text-muted">{{ $client->user->created_at->format('d/m/Y') }}</em></td>
                        
                        <td class="d-none d-sm-table-cell font-size-base">
                            <span class="badge badge-warning">AGUARDANDO APROVAÇÃO</span>
                        </td>
                        <td class="text-center">
                            <a href="{{ route('clients.edit', $client->id) }}" data-toggle="tooltip" title="Editar" data-placement="left">
                                <i class="fa fa-pencil-alt"></i>
                            </a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

resources/views/clients/create.blade.php
@extends('layouts.backend')

@section('content')
<!-- Hero -->
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Produtoras</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">App</li>
                    <li class="breadcrumb-item">Produtoras</li>
                    <li class="breadcrumb-item active" aria-current="page">Nova</li>
                </ol>
            </nav>
        </div>
   </div>
</div>
<!-- END Hero -->
<div class="content">
    <a href="{{ route('clients.index') }}" class="btn btn-primary push">Voltar</a>

    @if ($errors->any())
        <div class="alert alert-danger" role="alert">
            <p class="mb-0">Verifique os seguintes erros:</p>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Produtoras</h3>
        </div>
        <div class="block-content">
                <form action="{{ route('clients.store') }}" method="POST">
                @csrf
                <h2 class="content-heading pt-0">Nova produtora</h2>
                <div class="row push">
                    <div class="col-lg-4">
                        <p class="text-muted">
                            Hora de cadastrar uma nova produtora no sistema, ela poderá criar um carrinho de interesses, com os agenciados que ela selecionar! :)
                        </p>
                    </div>
                    <div class="col-lg-8 col-xl-5">
                        <div class="form-group">
                            <label for="example-text-input">Nome *</label>
                            <input type="text" class="form-control" name="name" placeholder="" value="{{ old('name') }}">
                        </div>
                        <div class="form-group">
                            <label for="example-text-input">Email *</label>
                            <input type="email" class="form-control" name="email" placeholder="" value="{{ old('email') }}">
                        </div>
                        <div class="form-group form-row">
                            <div class="col-6">
                                <label for="contact">Nome contato *</label>
                                <input type="text" class="form-control" name="contact" placeholder="" value="{{ old('contact') }}">
                            </div>
                            <div class="col-6">
                                <label for="phone_number">Telefone *</label>
                                <input type="text" class="form-control" name="phone_number" placeholder="" value="{{ old('phone_number') }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="example-text-input">Senha</label>
                            <input type="password" class="form-control" name="password" placeholder="">
                        </div>
                        <div class="form-group">
                            <label for="example-text-input">Confirma senha</label>
                            <input type="password" class="form-control" name="password_confirmation" placeholder="">
                        </div>
                        <div class="form-group">
                            <label class="d-block">Status</label>
                            <div class="custom-control custom-radio custom-control-inline custom-control-primary">
                                <input type="radio" class="custom-control-input" id="status-active" name="status" checked value="1">
                                <label class="custom-control-label" for="status-active">Aprovado</label>
                            </div>
                            <div class="custom-control custom-radio custom-control-inline custom-control-warning ">
                                <input type="radio" class="custom-control-input" id="status-inactive" name="status" value="2">
                                <label class="custom-control-label" for="status-inactive">Aguardando</label>
                            </div>
                        </div>
                        <input type="hidden" name="level" value="3">
                        <div class="form-group"> 
                            <button type="submit" class="btn btn-primary">Salvar</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/clients/edit.blade.php
@extends('layouts.backend')

@section('content')
<!-- Hero -->
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Produtoras</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">App</li>
                    <li class="breadcrumb-item">Produtoras</li>
                    <li class="breadcrumb-item active" aria-current="page">Edição</li>
                </ol>
            </nav>
        </div>
   </div>
</div>
<!-- END Hero -->
<div class="content">
    <a href="{{ route('clients.index') }}" class="btn btn-primary push">Voltar</a>

    @if ($errors->any())
        <div class="alert alert-danger" role="alert">
            <p class="mb-0">Verifique os seguintes erros:</p>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Produtoras</h3>
        </div>
        <div class="block-content">
                <form action="{{ route('clients.update', $client->id) }}" method="POST">

                @csrf
                @method('PUT')

                <h2 class="content-heading pt-0">Editando produtora</h2>
                <div class="row push">
                    <div class="col-lg-4">
                        <p class="text-muted">
                            Hora de editar uma produtora. Para isso basta preencher os dados que seguem. Vale lembrar que é muito importante você manter os dados sempre atualizados.
                        </p>
                    </div>
                    <div class="col-lg-8 col-xl-5">
                        <div class="form-group">
                            <label for="example-text-input">Nome *</label>
                            <input type="text" class="form-control" name="name" value="{{ old('name', $client->user->name) }}">
                        </div>
                        <div class="form-group">
                            <label for="example-text-input">Email *</label>
                            <input type="email" class="form-control" name="email" value="{{ old('email', $client->user->email) }}">
                        </div>
                        <div class="form-group form-row">
                            <div class="col-6">
                                <label for="contact">Nome contato *</label>
                                <input type="text" class="form-control" name="contact" placeholder="" value="{{ old('contact', $client->contact) }}">
                            </div>
                            <div class="col-6">
                                <label for="phone_number">Telefone *</label>
                                <input type="text" class="form-control" name="phone_number" placeholder="" value="{{ old('phone_number', $client->phone_number) }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="example-text-input">Senha</label>
                            <input type="password" class="form-control" name="password">
                        </div>
                        <div class="form-group">
                            <label for="example-text-input">Confirma senha</label>
                            <input type="password" class="form-control" name="password_confirmation">
                        </div>
                        <div class="form-group">
                            <label class="d-block">Status</label>
                            <div class="custom-control custom-radio custom-control-inline custom-control-primary">
                                <input type="radio" class="custom-control-input" id="status-active" name="status" {{ $client->status == 1 ? 'checked' : '' }} value="1">
                                <label class="custom-control-label" for="status-active">Aprovado</label>
                            </div>
                            <div class="custom-control custom-radio custom-control-inline custom-control-warning ">
                                <input type="radio" class="custom-control-input" id="status-inactive" name="status" {{ $client->status == 2 ? 'checked' : '' }} value="2">
                                <label class="custom-control-label" for="status-inactive">Aguardando</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Salvar</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/clients/index.blade.php
@extends('layouts.backend')

@section('content')
<!-- Hero -->
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Produtoras</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">App</li>
                    <li class="breadcrumb-item">Produtoras</li>
                    <li class="breadcrumb-item active" aria-current="page">Todas</li>
                </ol>
            </nav>
        </div>
   </div>
</div>
<!-- END Hero -->
<div class="content">
    <a href="{{ route('clients.create') }}" class="btn btn-primary push">Nova produtora</a>

    @if ($message = Session::get('success'))
    <div class="alert alert-success d-flex align-items-center" role="alert">
        <div class="flex-00-auto">
            <i class="fa fa-fw fa-check"></i>
        </div>
        <div class="flex-fill ml-3">
            <p class="mb-0">{{$message}}</p>
        </div>
    </div>
    @endif


    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Produtoras</h3>
        </div>
        <div class="block-content">
            <p>
                Aqui você encontra a lista de produtoras que você aprovou previamente a fazer parte do sistema. Elas estão aptas a fazer solicitações de lista de agenciados!
            </p>
            <table class="table table-striped table-hover table-borderless table-vcenter font-size-sm">
                <thead>
                    <tr class="text-uppercase">
                        <th class="text-center" style="width: 50px;">#</th>
                        <th>NOME</th>
                        <th class="text-center" style="width: 200px;">CADASTRO</th>
                        <th class="text-center" style="width: 200px;">STATUS</th>
                        <th class="text-center" style="width: 100px;">AÇÕES</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($clients as $client)
                    <tr>
                        <th class="text-center" scope="row">{{ ++$i }}</th>
                        <td>
                            <div class="font-w600 font-size-base">{{ $client->user->name }}</div>
                            <div class="text-muted">{{ $client->user->email }}</div>
                        </td>
                        <td class="text-center font-size-base">
                            {{ $client->user->created_at->format('d/m/Y') }}
                        </td>
                        
                        <td class="text-center">
                            <span class="badge badge-success">APROVADO</span>
                        </td>
                        <td class="text-center">
                            <div class="btn-group">
                                <a href="{{ route('clients.edit', $client->id) }}" class="btn btn-sm btn-primary" data-toggle="tooltip" title="Editar" data-placement="left">
                                    <i class="fa fa-pencil-alt"></i>
                                </a>
                                <a href="{{ route('clients.edit', $client->id) }}" class="btn btn-sm btn-primary" data-toggle="tooltip" title="Novo pedido" data-placement="left">
                                    <i class="fa fa-box-open"></i>
                                </a>
                                <a href="{{ route('clients.edit', $client->id) }}" class="btn btn-sm btn-primary" data-toggle="tooltip" title="Histórico de pedidos" data-placement="left">
                                    <i class="fa fa-cubes"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection