routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['middleware' => 'lang'], function() {

    //SITE - todas as rotas em portugues
    Route::get('/', 'SiteController@getIndex')->name('home');
    Route::get('/logout', 'SiteController@getLogout')->name('logout');

    Route::get('/elencos', 'SiteController@getElencos')->name('elencos');
    Route::post('/elencos', 'SiteController@postElencos');

    Route::get('/elenco/{slug}', 'SiteController@getElencoPerfil')->name('elencos.profile');

    Route::get('/trabalhos', 'SiteController@getTrabalhos')->name('trabalhos');
    Route::get('/trabalho/{slug}', 'SiteController@getTrabalho');

    Route::get('/agencia', 'SiteController@getAgencia')->name('agencia');
    Route::get('/contato', 'SiteController@getContato')->name('contato');
    Route::post('/send', 'SiteController@sendContact')->name('send');


    Route::get('/cadastro', 'SiteController@getCadastro')->name('cadastro');

    Route::group(['middleware'=> ['check.agenciado']], function(){
        Route::get('/perfil', 'SiteController@getProfle')->name('perfil');
        Route::get('/perfil/editar', 'SiteController@getProfleEditar');
    });

     //Cliente
     Route::group(['middleware'=> ['check.cliente']], function(){
         Route::get('/cliente', 'SiteController@Cliente')->name('cliente');
         Route::get('/cliente/editar', 'SiteController@getClienteEditar');
     });
});


Route::get('/login/facebook','SocialAuthController@login');
Route::get('/retorno/facebook','SocialAuthController@retorno');

Route::get('/login/facebook2','SocialAuthController@login2');
Route::get('/retorno/facebook2','SocialAuthController@retorno2');





// Route::group(['middleware' => 'SiteLogin'], function(){

// });

Auth::routes();

//DASHBOARD - todas as rotas em ingles

Route::get('/admin', function () {
    return redirect()->route('login');
});

Route::post('/login-agenciado', 'SiteController@LoginAgenciado');
Route::post('/registrar-agenciado', 'SiteController@RegisterAgenciado');

Route::post('/login-cliente', 'SiteController@LoginCliente');
Route::post('/registrar-cliente', 'SiteController@RegisterCliente');

Route::group(['middleware' => ['auth']], function () {

    // Dashboard
    Route::view('/dashboard', 'dashboard');

    // Cart
    Route::resource('/carts', 'CartController');
    Route::get('/carts/{cart}/preview/{profile}', 'CartController@previewPDF')->name('profile.preview');
    Route::get('/carts/{cart}/send', 'CartController@sendCart')->name('carts.send');

    // Profile
    Route::resource('/profiles', 'ProfileController');
    Route::get('/profiles/solicitation', 'ProfileController@solicitation');
    Route::resource('/profiles', 'ProfileController');

    // Skill
    Route::resource('/skills', 'SkillController');

    // Client
    Route::get('/clients/solicitation', 'ClientController@solicitation');
    Route::get('/clients/awaiting', 'ClientController@awaiting');
    Route::resource('/clients', 'ClientController');

    // Post
    Route::resource('/posts', 'PostController');

    // User
    Route::get('/profile', 'UserController@profile');
    Route::post('/profile', 'UserController@updateProfile');

    // Profile Change Request
    Route::get('/profileChangeRequest/{id}', 'ProfileChangeRequestsController@accept')
        ->name('profileChangeRequests.accept');
    // Route::post('/profileChangeRequest/{id}', 'ProfileChangeRequestsController@accept')
    //     ->name('profileChangeRequests.accept');

    Route::resource('/users', 'UserController');
});

app/Skill.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Skill extends Model
{
    protected $fillable = [
        'name', 'status'
    ];
}

app/Http/Controllers/SkillController.php
<?php

namespace App\Http\Controllers;

use App\Skill;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SkillController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $skills = Skill::orderBy('name', 'asc')->latest()->paginate(10);

        return view('skills.index', compact('skills'))
            ->with('i', (request()->input('page', 1) - 1) * 10);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('skills.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'name' => 'required'
        ]);

        Skill::create($request->all());

        return redirect()->route('skills.index')
            ->with('success', 'Característica criada com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Skill  $skill
     * @return \Illuminate\Http\Response
     */
    public function show(Skill $skill)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Skill  $skill
     * @return \Illuminate\Http\Response
     */
    public function edit(Skill $skill)
    {
        return view('skills.edit', compact('skill'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Skill  $skill
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Skill $skill)
    {
        request()->validate([
            'name' => 'required'
        ]);

        $skill->update($request->all());

        return redirect()->route('skills.index')
                        ->with('success','Característica atualizada com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Skill  $skill
     * @return \Illuminate\Http\Response
     */
    public function destroy(Skill $skill)
    {
        $skill->delete();

        return redirect()->route('skills.index')
                        ->with('success','Característica deletada com sucesso!');
    }
}

resources/views/skills/create.blade.php
@extends('layouts.backend')

@section('content')
<!-- Hero -->
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Características</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">App</li>
                    <li class="breadcrumb-item">Características</li>
                    <li class="breadcrumb-item active" aria-current="page">Nova</li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<!-- END Hero -->
<div class="content">
    <a href="{{ route('skills.index') }}" class="btn btn-primary push">Voltar</a>

    @if ($errors->any())
        <div class="alert alert-danger" role="alert">
            <p class="mb-0">Verifique os seguintes erros:</p>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Características</h3>
        </div>
        <div class="block-content">
                <form action="{{ route('skills.store') }}" method="POST">
                @csrf
                <h2 class="content-heading pt-0">Nova característica</h2>
                <div class="row push">
                    <div class="col-lg-4">
                        <p class="text-muted">
                            Hora de cadastrar uma nova característica, para tal basta preencher o campo que segue e clicar em salvar!
                        </p>
                    </div>
                    <div class="col-lg-8 col-xl-5">
                        <div class="form-group">
                            <label for="example-text-input">Característica</label>
                            <input type="text" class="form-control" name="name" placeholder="">
                        </div>
                        <div class="form-group">
                            <label class="d-block">Status</label>
                            <div class="custom-control custom-radio custom-control-inline custom-control-primary">
                                <input type="radio" class="custom-control-input" id="status-active" name="status" checked value="1">
                                <label class="custom-control-label" for="status-active">Ativo</label>
                            </div>
                            <div class="custom-control custom-radio custom-control-inline custom-control-primary">
                                <input type="radio" class="custom-control-input" id="status-inactive" name="status" value="2">
                                <label class="custom-control-label" for="status-inactive">Inativo</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Salvar</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/skills/edit.blade.php
@extends('layouts.backend')

@section('content')
<!-- Hero -->
<div class="bg-body-light">
        <div class="content content-full">
            <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
                <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Características</h1>
                <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">App</li>
                        <li class="breadcrumb-item">Características</li>
                        <li class="breadcrumb-item active" aria-current="page">Edição</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
    <!-- END Hero -->
<div class="content">
    <a href="{{ route('skills.index') }}" class="btn btn-primary push">Voltar</a>

    @if ($errors->any())
        <div class="alert alert-danger" role="alert">
            <p class="mb-0">Verifique os seguintes erros:</p>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Característica</h3>
        </div>
        <div class="block-content">
            <form action="{{ route('skills.update', $skill->id) }}" method="POST">

                @csrf
                @method('PUT')

                <h2 class="content-heading pt-0">Editando característica</h2>
                <div class="row push">
                    <div class="col-lg-4">
                        <p class="text-muted">
                            Aqui você pode e deve fazer as alterações necessárias para determinada característica.
                        </p>
                    </div>
                    <div class="col-lg-8 col-xl-5">
                        <div class="form-group">
                            <label for="example-text-input">Característica</label>
                            <input type="text" class="form-control" name="name" placeholder="" value="{{ $skill->name }}">
                        </div>
                        <div class="form-group">
                            <label class="d-block">Status</label>
                            <div class="custom-control custom-radio custom-control-inline custom-control-primary">
                            <input type="radio" class="custom-control-input" id="status-active" name="status" {{ $skill->status == 1 ? 'checked' : '' }} value="1">
                                <label class="custom-control-label" for="status-active">Ativo</label>
                            </div>
                            <div class="custom-control custom-radio custom-control-inline custom-control-primary">
                                <input type="radio" class="custom-control-input" id="status-inactive" name="status" {{ $skill->status == 2 ? 'checked' : '' }} value="2">
                                <label class="custom-control-label" for="status-inactive">Inativo</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Salvar</button>
                        </div>
                    </div>
                </div> 
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/skills/index.blade.php
@extends('layouts.backend')

@section('content')
<!-- Hero -->
<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill font-size-h2 font-w400 mt-2 mb-0 mb-sm-2">Características</h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">App</li>
                    <li class="breadcrumb-item">Características</li>
                    <li class="breadcrumb-item active" aria-current="page">Todas</li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<!-- END Hero -->
<div class="content">
    
    <a href="{{ route('skills.create') }}" class="btn btn-primary push">Nova característica</a>

    @if ($message = Session::get('success'))
    <div class="alert alert-success d-flex align-items-center" role="alert">
        <div class="flex-00-auto">
            <i class="fa fa-fw fa-check"></i>
        </div>
        <div class="flex-fill ml-3">
            <p class="mb-0">{{$message}}</p>
        </div>
    </div>
    @endif

    <div class="block block-rounded block-bordered">
        <div class="block-header block-header-default">
            <h3 class="block-title">Características</h3>
            <div class="block-options">
                <div class="block-options-item">
                    
                </div>
            </div>
        </div>
        <div class="block-content">
            <table class="table table-striped table-hover table-borderless table-vcenter font-size-sm">
                <thead>
                    <tr class="text-uppercase">
                        <th class="text-center" style="width: 50px;">#</th>
                        <th class="">DESCRIÇÃO</th>
                        <th class="text-center" style="width: 100px;">STATUS</th>
                        <th class="text-center" style="width: 100px;">AÇÕES</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($skills as $skill)
                    <tr>
                        <th class="text-center" scope="row">{{ ++$i }}</th>
                        <td class="font-w600 font-size-base">
                            {{ $skill->name }}
                        </td>
                        <td class="text-center">
                            @if ($skill->status == 1)
                            <span class="badge badge-success">ATIVO</span>
                            @else
                            <span class="badge badge-danger">INATIVO</span>
                            @endif
                        </td>
                        <td class="text-center">
                            <div class="btn-group">
                                <a  href="{{ route('skills.edit', $skill->id) }}" class="btn btn-sm btn-primary" data-toggle="tooltip" title="Editar" data-placement="left">
                                    <i class="fa fa-pencil-alt"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    
    {!! $skills->links() !!}
    
</div>
@endsection